---

- name: Copy docker debian repository file
  template: src=etc/apt/sources.list.d/docker.list.j2 dest=/etc/apt/sources.list.d/docker.list
  register: docker_repo


- name: Docker repository is HTTPS so it needs apt https transport to be installed
  apt: name=apt-transport-https state=present
  when: docker_repo.changed
  
- name: Add docker's key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - 
  when: docker_repo.changed
  
- name: Update apt to get docker
  apt: update_cache=yes
  when: docker_repo.changed
  
- name: Installs docker-ce
  apt: name=docker-ce state=present

- name: Installs docker-ce-cli
  apt: name=docker-ce-cli state=present

- name: Installs containerd.io
  apt: name=containerd.io state=present

- name: Prepare Installation of docker-compose ; creates a folder into opt
  file: dest=/opt/docker-compose/1.16.0 state=directory
    
- name: Installs docker-compose by getting url
  get_url: url=https://github.com/docker/compose/releases/download/1.16.0/docker-compose-Linux-x86_64 dest=/opt/docker-compose/1.16.0/docker-compose mode=755

- name: Creats symlink
  file: src=/opt/docker-compose/1.16.0/docker-compose dest=/usr/local/bin/docker-compose state=link

- name: Adds user to docker group
  user: name={{docker_user}} append=true groups=docker
  when: docker_user is defined
  