---

- apt: update_cache=yes cache_valid_time=3600
  tags: common_debian

- include_tasks: bash.yml
  tags: bash, common_debian
   
- include_tasks: utils.yml
  tags: common_debian,common_debian_utils

- include_tasks: locale.yml
  tags: common_locale, common_debian

- include_tasks: eol_cron.yml
  tags: eol_cron, common_debian
  