---

- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: present

- name: Define vim as the default editor
  ansible.builtin.lineinfile:
    dest: /etc/bash.bashrc
    line: "export EDITOR=vim"

- name: Vim configuration file for current user
  ansible.builtin.copy:
    src: vimrc
    dest: ~/.vimrc
    mode: '0600'
  when: groundzero.tools.vim.disable_mouse is not defined or not groundzero.tools.vim.disable_mouse
