---
- name: Iptables rules for OVH dedicated servers
  ansible.builtin.template:
    src: etc/iptables.d/80_ovh_dedicated.conf.j2
    dest: /etc/iptables.d/80_ovh_dedicated.conf
    mode: "0600"
  tags: system_iptables
  notify:
    - iptables restart

- name: Ensure authorized_keys2 exists
  ansible.builtin.copy:
    content: ""
    dest: /root/.ssh/authorized_keys2
    force: false
    mode: "0600"

- name: Install OVH key (see https://docs.ovh.com/fr/dedicated/ovh-ssh-key/)
  ansible.builtin.lineinfile:
    path: /root/.ssh/authorized_keys2
    regexp: "tpArwDdonc7SLQ26uR9nabw"
    line: >
      from="{{ ovh_dedicated_ips | join(',') }}" ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAACAQDRpA0gxYQAL4HnRrFDlKsfjy6nEihOBsg6dgwR+mYee7nhTaCUqKXIlh3aJaRsiZcx4
      Uapq8f8NiU0g+SGWxCSbv7v4wbHfTX+brSJ+28bSUXp3B08iIcAiZgXIOBS+r++W1yJYUJRuMV934rmAvbyRhkr6rqZLp0Mr7
      3AKnKlxR/UzN0VyA5JCXQPLAoYkm505WbwCjLKZowDobwpjx0968zkctYCpCxvJ3Wr8f0qEVtwMHawsgv1wmJuIF7689LA7U0
      i2yXaPrtwPdjWZsrc5YSUZL8JQTDW4PnQLiYild+YKcMMHp12bQKNvJgBStHsLlxx0hCRYoiYdMFuN0f951Vc16EmHH+7qgwC
      IGeeD7npyhdUevwxlY2IAEka3udOBM0t2koQlGIGckBJlAgL/W2flrvz1noSwIii6HX836lLj80djm4W0LhXu8M+nlQvDE754
      9srqB3+rDJ18po79+btEHirH/vfkB+X9rFd6hyHX27cygs2TpHIt+OmKkt9UB8gQy6tHX/OK2BR5v9ToBprPNAs2d/iH/K2mp
      J0jHFI3FrCg9sqkz/lPwAl8bjCPZiUKU5+o+0O81MSNwqbQBl042n0Sqq9LxWP9TzxHT1GyE4LoV9NR4VHppkn+P22JO3o6B1
      2Q5//pUgrw+VtpArwDdonc7SLQ26uR9nabw==
      support@cache-ng
  tags: ssh,common
