---

- name: Install bind
  apt: name=bind9 state=present
  notify: bind_restart
  
- name: Create log dir for bind
  file: state=directory dest=/home/log/named owner=bind group=bind mode=755

- name: Add access to /home/log/named for bind into apparmor
  lineinfile:
    path: /etc/apparmor.d/local/usr.sbin.named
    line: "/home/log/named/ rw,"
  notify: apparmor_restart
  
- name: Add access to /home/log/named contents for bind into apparmor
  lineinfile:
    path: /etc/apparmor.d/local/usr.sbin.named
    line: "/home/log/named/** rw,"
  notify: apparmor_restart

- name: Flush handlers to reload apparmor with bind
  meta: flush_handlers

- name: Add logging configuration to /etc/bind/named.conf.local
  blockinfile:
    path: /etc/bind/named.conf.local
    insertafter: BOF
    marker: // {mark} LOG TO FILE
    block: |
      logging {
              channel named_file {
                      file "/var/log/named/named.log" versions 10 size 1m;
              };
              category default { named_file;};
      };
  notify: bind_restart
  
- name: Ensure local resolver is used first into /etc/resolv.conf
  lineinfile: name=/etc/resolv.conf line="nameserver 127.0.0.1" insertbefore='BOF'

- name: Disable listening on IP v6 in bind options
  lineinfile: regexp="(.*listen-on-v6.*)" line="	//listen-on-v6 { any; };" path=/etc/bind/named.conf.options
  when: disable_bind_on_ip_6 is defined and disable_bind_on_ip_6 == true
  notify: bind_restart

- name: Create bind service local configuration directory
  file: path=/etc/systemd/system/bind9.service.d state=directory
  when: disable_bind_on_ip_6 is defined and disable_bind_on_ip_6 == true
  
- name: Override service startup command to force IP V4 only
  copy: src=etc/systemd/system/bind9.service.d/{{bind_local_conf}} dest=/etc/systemd/system/bind9.service.d/local.conf
  when: disable_bind_on_ip_6 is defined and disable_bind_on_ip_6 == true
  notify:
    - bind_restart
    - systemd reload
    