---
#################################
# Role installing :
# - A set of vhosts for apache
# - mod_jk if needed to connect to tomcat using modjk
# - log rotation cron script with optional backup for apache

#################################
# Dependencies :
# - apache : apache role is not included and must be included before calling this role

#################################
# Parameters outside of role:
# - apache_vhosts_serverindex : can be used to restrict generation of only one vhost idenfitified by its serverindex
# Example ansible -e apache_vhosts_serverindex=001
# - certbot_delete_certificate : can be used to request that the currently installed certificate be removed
# Example ansible -e certbot_delete_certificate=true

#################################
# Parameters :
# - apache_vhosts_serverindex : can be used to restrict
# - apache_vhosts_default404 : if defined, will add a 000_default.conf that will cause 404 for all unknown hosts (will precede the one from apache's role)
# - apache_backuplogs : if defined, the directory to use for rsyncing logs
# - apache_java_webapp1 (optional) : if defined will install a vhost on webapp1 using this value as name
# - apache_java_servername (mandatory if apache_java_webapp1 exists) : defines the main domainname of the vhost
# - apache_java_serveralias (mandatory if apache_java_webapp1 exists) : defines the domain aliases (space separated list) of the vhost
# - apache_java_letsencrypt : if defined, enables HTTPs through Let's encrypt of the vhost
# - apache_java_letsencrypt_domains_main (mandatory if apache_java_letsencrypt is defined) :  defines the main domain used to create the letsencrypt certificate
# - apache_java_letsencrypt_domains_others (mandatory if apache_java_letsencrypt is defined) :  defines comma separated list of alternative domains used to create the letsencrypt certificate
# - apache_reverse_proxy: if defined, the local net used by the reverse prox
# - apache_java_rewriterules: if defined, this rewrite rules file will be included into the generated vhost
# - apache_vhosts_isolated_authorized_ips (mandatory if on vhost is isolated) : defines the list of authorized ips.
# - apache_java_httpToHttpsRewriteRules (optional) : defines RewriteRules file to be used for all redirections from HTTP to HTTPs
# - apache_java_vhosts : list of vhost, see below for details about properties for each vhost
# - apache_letsencrypt_autoreload: if defined and true the certbot notify handler script will automatically reload apache
# - apache_java_gzip : enables/disables gzip compression (more often with apache_java_gzip=false to disable it). Default : true
# - apache_java_vhost_auth_users : List of users ({login: , password: } for the basic authentication. Passwords are the encrypted passwords as generated by htpasswd. If defined protects the entire site.
# - apache_vhosts_modjk : if defined and true, installs modjk and configures it to connect to tomcat.

# - Each vhost in apache_java_vhosts can contains following :
#   serverindex          : index of the vhost file to create
#   servername				   : main domain of the vhost
#		serveralias				   : domain alias (www. for instance ) list of the domain (coma separated list)
#   include              : An absolute path to a file to include in the vhost
#   letsencrypt          : enables HTTPS using LetsEncrypt
#		letsencrypt_web      : if defined (true) enables automatic renewal of letsencrypt certificate via web (supercedes default which is via dns)
#		selfsigned           : enables HTTPS using SelfSigned certificate (previously generated using apache_selfsigned role)
#		externalcertificate  : enables HTTPS using an external certificate, content of this variable will be used by appending '.cert', '.key' and '.chain'.
#								Example : /etc/apache2/lrv/ssl/www.mydomain.com/www.mydomain.com
#	isolated				     : isolates the domain (you have to define apache_vhosts_isolated_authorized_ips
#	parking					     : puts the domain to parking if defined
#	httpToHttpsRewriteRules	: if defined, overrides apache_java_httpToHttpsRewriteRules for the file to be used for all redirectons from HTTP to HTTPs for this VHOST
#	hsts					       : If defined, sets the HSTS header
#   securityHeaders         : If defined, add X-FRAME-OPTIONS, X-XSS-Protection and  X-Content-Type-Options
#	redirect_http_to_https : Installs rewrite rules from http to https. If not defined, default true.
#   tls12Min                : If defined and true, this vhost will support tls1.2 and further. Otherwise supports Tls1.0+

#################################
# Example :
#    - {role: apache_java,
#             apache_vhosts_default404: true,
#             apache_backuplogs: /mnt/cifsbackup/apachelogs,
#             apache_reverse_proxy: '42.42.42.42/24',
#             apache_letsencrypt_autoreload: true,
#             apache_java_gzip: false,
#             apache_java_vhosts: [
#             {
#               serverindex: '001',
#               servername:  'www.mydomain.com',
#               letsencrypt : true,
#               hsts: true,
#               securityHeaders: true

#             }
#             ]
#      }

- import_tasks: java_vhosts.yml
  tags:
    - apache_vhosts
    - apache_vhosts_common

- import_tasks: modjk.yml
  tags:
    - apache_vhosts
    - apache_vhosts_modjk
  when: apache_vhosts_modjk is defined and apache_vhosts_modjk

#Replaced with include: . Waiting for fix of https://github.com/ansible/ansible/issues/31673
- include_tasks: vhost.yml
  with_items: "{{apache_vhosts}}"
  loop_control:
    loop_var: apache_java_vhost
  when: apache_vhosts is defined and (not apache_vhosts_serverindex is defined or apache_vhosts_serverindex is search(apache_java_vhost.serverindex))
  tags:
    - apache_vhosts
    - system_cron
